name = "Baraka-sonko-electronics1"
compatibility_date = "2026-01-14"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sonko"
database_id = "9fc679a8-c734-4322-a205-ae91a5a318dd"

# âœ… ADD THIS (R2 binding)
[[r2_buckets]]
binding = "R2"
bucket_name = "sonko"
