name = "baraka-sonko-electronics1"
compatibility_date = "2026-02-01"


pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sonko"
database_id = "0777b428-f6f5-4900-bbd5-d6694ccc8586"
